Repository SU-SWS/sdss_profile, pull requests merged in 2022-08, with the labels that each got.

#28 SDSS: h2 to h3 fix and button size
  config/sync/core.entity_view_display.paragraph.stanford_entity.default.yml
  config/sync/core.entity_view_display.paragraph.stanford_lists.default.yml
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/components/secondary-navigation/_secondary-navigation.scss
  themes/sdss_subtheme/src/scss/utilities/mixins/_buttons.scss
Labels: size/xs

#29 Sdss events - list, teasers and page.
  config/sync/views.view.stanford_events.yml
  themes/sdss_subtheme/dist/assets/svg/caret-right.svg
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/components/events/_events-list.scss
  themes/sdss_subtheme/src/scss/components/events/_events.scss
  themes/sdss_subtheme/src/scss/components/events/index.scss
  themes/sdss_subtheme/src/scss/components/index.scss
  themes/sdss_subtheme/src/scss/components/main-navigation/_main-navigation.scss
  themes/sdss_subtheme/src/scss/components/news/_news-list.scss
  themes/sdss_subtheme/src/scss/components/news/_news.scss
  themes/sdss_subtheme/src/scss/components/news/index.scss
  themes/sdss_subtheme/src/scss/components/secondary-navigation/_filter_by_menu.scss
  themes/sdss_subtheme/src/scss/components/secondary-navigation/_secondary-navigation.scss
  themes/sdss_subtheme/src/scss/components/secondary-navigation/index.scss
  themes/sdss_subtheme/src/scss/utilities/mixins/_buttons.scss
  themes/sdss_subtheme/src/scss/utilities/mixins/_link-icon.scss
  themes/sdss_subtheme/src/scss/utilities/variables/_colors.scss
  themes/sdss_subtheme/templates/components/events/pattern-events-list--views-row.html.twig
  themes/sdss_subtheme/templates/components/news-vertical-teaser/pattern-news-vertical-teaser--layout.html.twig
Labels: size/m

#30 first pass at image styles
  config/sync/core.entity_view_display.media.image.default.yml
  config/sync/core.entity_view_display.node.stanford_news.stanford_card.yml
  config/sync/core.entity_view_display.paragraph.stanford_card.default.yml
  config/sync/image.style.card_3_2_1200x800_.yml
  config/sync/image.style.card_3_2_1920x1280_.yml
  config/sync/image.style.card_3_2_480x320_.yml
  config/sync/image.style.card_3_2_960x640_.yml
  config/sync/responsive_image.styles.card_3_2.yml
  config/sync/views.view.stanford_news.yml
Labels: size/s

#32 Stanford profile updates 20220803
  config/sync/core.entity_form_display.paragraph.stanford_banner.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_card.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_entity.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_gallery.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_lists.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_media_caption.default.yml
  config/sync/core.extension.yml
  config/sync/editor.editor.stanford_html.yml
  config/sync/editor.editor.stanford_minimal_html.yml
  content/menu_link_content/178b9e51-c3bb-4cd5-a3ac-fe241e27f083.yml
  content/menu_link_content/26a314fe-33aa-4660-b06a-97b26dc75baf.yml
  content/menu_link_content/3e24cd94-5f2b-4fb2-806c-bcb830cdc2dc.yml
  content/menu_link_content/752de90b-4130-402f-8601-57f8d916799c.yml
  content/menu_link_content/a5f9f185-b376-4cab-b3bd-dc3b03617cea.yml
  content/menu_link_content/bdf424e8-7106-414d-b333-7f5add6e8c8a.yml
  content/menu_link_content/c2c22d8b-eb7c-4804-9332-4ec2aff3391a.yml
  content/menu_link_content/d91b714a-4609-41c5-a9c4-d8140ed3a764.yml
  content/menu_link_content/e635159f-4b50-4016-bbf6-41113adbff65.yml
  modules/stanford_person/modules/stanford_person_importer/src/Config/ConfigOverrides.php
  modules/stanford_person/modules/stanford_person_importer/tests/src/Unit/Config/ConfigOverridesTest.php
  modules/stanford_profile_helper/src/EventSubscriber/EntityEventSubscriber.php
  modules/stanford_profile_helper/src/EventSubscriber/PreprocessEventSubscriber.php
  modules/stanford_profile_helper/src/Plugin/Validation/Constraint/MenuLinkItemConstraint.php
  modules/stanford_profile_helper/src/Plugin/Validation/Constraint/MenuLinkItemConstraintValidator.php
  modules/stanford_profile_helper/stanford_profile_helper.module
  modules/stanford_profile_helper/stanford_profile_helper.services.yml
  modules/stanford_profile_helper/tests/src/Kernel/EventSubscriber/EntityEventSubscriberTest.php
  modules/stanford_profile_helper/tests/src/Unit/Plugin/Validation/Constraint/MenuLinkItemConstraintValidatorTest.php
  modules/stanford_profile_styles/js/colorbox.js
  modules/stanford_profile_styles/stanford_profile_styles.libraries.yml
  modules/stanford_text_editor/tests/src/Kernel/StanfordTextEditorTest.php
  tests/codeception/acceptance/Content/DefaultContentCest.php
  tests/codeception/functional/Content/BasicPageParagraphsCest.php
  tests/codeception/functional/Paragraphs/BannerCest.php
  tests/codeception/functional/Paragraphs/EntityReferenceCest.php
  tests/codeception/functional/Paragraphs/WYSIWYGCest.php
  themes/stanford_basic/dist/assets/fonts/fa-brands-400.eot
  themes/stanford_basic/dist/assets/fonts/fa-brands-400.ttf
  themes/stanford_basic/dist/assets/fonts/fa-brands-400.woff
  themes/stanford_basic/dist/assets/fonts/fa-brands-400.woff2
  themes/stanford_basic/dist/assets/fonts/fa-regular-400.eot
  themes/stanford_basic/dist/assets/fonts/fa-regular-400.ttf
  themes/stanford_basic/dist/assets/fonts/fa-regular-400.woff
  themes/stanford_basic/dist/assets/fonts/fa-regular-400.woff2
  themes/stanford_basic/dist/assets/fonts/fa-solid-900.eot
  themes/stanford_basic/dist/assets/fonts/fa-solid-900.ttf
  themes/stanford_basic/dist/assets/fonts/fa-solid-900.woff
  themes/stanford_basic/dist/assets/fonts/fa-solid-900.woff2
  themes/stanford_basic/dist/assets/svg/fa-brands-400.svg
  themes/stanford_basic/dist/assets/svg/fa-regular-400.svg
  themes/stanford_basic/dist/assets/svg/fa-solid-900.svg
  themes/stanford_basic/dist/js/base.js
  themes/stanford_basic/dist/js/base.js.map
  themes/stanford_basic/dist/js/behaviors.js
  themes/stanford_basic/dist/js/behaviors.js.map
  themes/stanford_basic/dist/templates/decanter/components/global-footer/global-footer.twig
  themes/stanford_basic/src/js/stanford_basic.behavior.js
  themes/stanford_basic/stanford_basic.libraries.yml
  themes/stanford_basic/yarn.lock
Labels: size/xl

#33 Sdss text bugs
  config/sync/image.style.stanford_circle.yml
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/components/button/_button.scss
  themes/sdss_subtheme/src/scss/components/card/_card.scss
  themes/sdss_subtheme/src/scss/components/row-backgrounds/_row-background-colors.scss
  themes/sdss_subtheme/src/scss/theme/_link.scss
  themes/sdss_subtheme/src/scss/theme/_wysiwyg.scss
  themes/sdss_subtheme/src/scss/utilities/mixins/_buttons.scss
Labels: size/xs

#34 SDSS-141: Allow greater menu depth in secondary nav
  themes/sdss_subtheme/sdss_subtheme.info.yml
  themes/sdss_subtheme/sdss_subtheme.libraries.yml
  themes/sdss_subtheme/templates/menus/macros/secondary-nav-menu.twig
  themes/sdss_subtheme/templates/menus/menu--secondary-nav.html.twig
Labels: size/xs

#36 Add theme viewer role
  config/sync/user.role.theme_viewer.yml
  themes/sdss_subtheme/templates/html.html.twig
Labels: size/xs

#35 Sdss text bugs
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/components/card/_card-variants.scss
  themes/sdss_subtheme/src/scss/components/card/_card.scss
  themes/sdss_subtheme/src/scss/components/card/_minimal-border.scss
  themes/sdss_subtheme/src/scss/components/card/_title.scss
  themes/sdss_subtheme/src/scss/components/card/_topic.scss
  themes/sdss_subtheme/src/scss/components/card/index.scss
  themes/sdss_subtheme/src/scss/components/local-footer/_local-footer.scss
  themes/sdss_subtheme/src/scss/components/row-backgrounds/_row-background-colors.scss
  themes/sdss_subtheme/src/scss/theme/_typography.scss
  themes/sdss_subtheme/src/scss/theme/_wysiwyg.scss
  themes/sdss_subtheme/src/scss/utilities/mixins/_buttons.scss
  themes/sdss_subtheme/src/scss/utilities/mixins/_links.scss
Labels: size/s

#37 SDSS-151, SDSS-152, SDSS-153 and change to ems from px.
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/components/card/_icon.scss
  themes/sdss_subtheme/src/scss/components/card/_title.scss
  themes/sdss_subtheme/src/scss/components/card/_topic.scss
  themes/sdss_subtheme/src/scss/components/row-backgrounds/_row-background-colors.scss
  themes/sdss_subtheme/src/scss/theme/_headings.scss
  themes/sdss_subtheme/src/scss/theme/_typography.scss
  themes/sdss_subtheme/src/scss/theme/_wysiwyg.scss
  themes/sdss_subtheme/src/scss/utilities/mixins/_buttons.scss
  themes/sdss_subtheme/src/scss/utilities/mixins/_typography.scss
Labels: size/s

#38 SDSS-161, SDSS-159, SDSS-158, SDSS-160, SDSS-163, SDSS-162
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/components/events/_events-list.scss
  themes/sdss_subtheme/src/scss/components/index.scss
  themes/sdss_subtheme/src/scss/components/main-navigation/_main-navigation.scss
  themes/sdss_subtheme/src/scss/components/news/_news-list.scss
  themes/sdss_subtheme/src/scss/components/node/_stanford-page.scss
  themes/sdss_subtheme/src/scss/components/node/index.scss
  themes/sdss_subtheme/src/scss/components/people/_people.scss
Labels: size/xs

#40 SDSS-154-155-156: Added spacer size field, template, and styles
  config/sync/core.entity_form_display.paragraph.stanford_spacer.default.yml
  config/sync/core.entity_view_display.paragraph.stanford_spacer.default.yml
  config/sync/core.extension.yml
  config/sync/field.field.paragraph.stanford_spacer.su_spacer_size.yml
  config/sync/field.storage.paragraph.su_spacer_size.yml
  config/sync/field.storage.paragraph_row.su_para_row_bgcolor.yml
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/components/all/_vertical-spacing.scss
  themes/sdss_subtheme/src/scss/components/all/index.scss
  themes/sdss_subtheme/src/scss/components/index.scss
  themes/sdss_subtheme/src/scss/components/main-navigation/_main-navigation.scss
  themes/sdss_subtheme/src/scss/components/spacer/_spacer.scss
  themes/sdss_subtheme/src/scss/components/spacer/index.scss
  themes/sdss_subtheme/templates/components/spacer/paragraph--stanford-spacer.html.twig
Labels: size/s

#39 updates to the secondary menu
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/components/secondary-navigation/_secondary-navigation.scss
Labels: size/xs

#42 SDSS-167: fixing basic page teaser. Removed Italics from SDSS-151
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/components/card/_card.scss
  themes/sdss_subtheme/src/scss/utilities/mixins/_typography.scss
Labels: size/xs

#41 SDSS-165: updated the news list and the news node.
  config/sync/core.entity_view_display.node.stanford_news.default.yml
  config/sync/core.entity_view_display.node.stanford_news.stanford_card.yml
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/components/card/_card.scss
  themes/sdss_subtheme/src/scss/components/local-footer/_local-footer.scss
  themes/sdss_subtheme/src/scss/components/news/_news.scss
  themes/sdss_subtheme/templates/components/news-vertical-teaser/pattern-news-vertical-teaser--layout.html.twig
  themes/sdss_subtheme/templates/components/news-vertical-teaser/pattern-news-vertical-teaser.html.twig
  themes/sdss_subtheme/templates/components/news-vertical-teaser/pattern-news-vertical-teaser.ui_patterns.yml
Labels: size/s

#43 SDSS-179: main nav and teaser and list fixes
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/components/events/_events-list.scss
  themes/sdss_subtheme/src/scss/components/main-navigation/_main-navigation.scss
  themes/sdss_subtheme/src/scss/components/news/_news.scss
  themes/sdss_subtheme/src/scss/components/people/_people.scss
  themes/sdss_subtheme/src/scss/components/secondary-navigation/_secondary-navigation.scss
  themes/sdss_subtheme/src/scss/theme/_link.scss
  themes/sdss_subtheme/src/scss/utilities/mixins/_links.scss
  themes/sdss_subtheme/templates/components/news-vertical-teaser/pattern-news-vertical-teaser.ui_patterns.yml
Labels: size/s

#46 Updating tests
  tests/codeception/acceptance/Content/NewsCest.php
  tests/codeception/functional/Paragraphs/EntityReferenceCest.php
Labels: size/xs

#44 SDSS-183: button moving fix
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/components/row-backgrounds/_row-background-colors.scss
  themes/sdss_subtheme/src/scss/theme/_link.scss
  themes/sdss_subtheme/src/scss/utilities/mixins/_buttons.scss
Labels: size/xs

#47 SDSS-184: updates to focus links and footer links
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/components/local-footer/_local-footer.scss
  themes/sdss_subtheme/src/scss/components/row-backgrounds/_row-background-colors.scss
  themes/sdss_subtheme/src/scss/theme/_link.scss
  themes/sdss_subtheme/src/scss/utilities/mixins/_buttons.scss
  themes/sdss_subtheme/src/scss/utilities/mixins/_links.scss
Labels: size/xs

#48 SDSS-214 SDSS-213: updated Intro and Quote style to use Decanter mixin
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/utilities/mixins/_typography.scss
Labels: size/xs

#49 SDSS-212: updating inline image captions to match the media with caption
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/theme/_wysiwyg.scss
Labels: size/xs

#50 SDSS-189 SDSS-189: fixes for the green background
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/components/row-backgrounds/_row-background-colors.scss
Labels: size/xs

#54 SDSS-199: Update menu behavior
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/components/secondary-navigation/_secondary-navigation.scss
  themes/sdss_subtheme/templates/menus/macros/nav-menu.twig
  themes/sdss_subtheme/templates/menus/menu--main.html.twig
  themes/sdss_subtheme/templates/menus/menu--secondary-nav.html.twig
Labels: size/s

#51 SDSS-205: focus state in top and side navigation
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/components/main-navigation/_main-navigation.scss
  themes/sdss_subtheme/src/scss/components/secondary-navigation/_secondary-navigation.scss
  themes/sdss_subtheme/src/scss/theme/_link.scss
  themes/sdss_subtheme/src/scss/utilities/mixins/_buttons.scss
  themes/sdss_subtheme/src/scss/utilities/mixins/_links.scss
Labels: size/xs

#52 SDSS-206, SDSS-216, SDSS-207
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/components/card/_card-variants.scss
  themes/sdss_subtheme/src/scss/components/node/_stanford-page.scss
  themes/sdss_subtheme/src/scss/components/row-backgrounds/_row-background-colors.scss
Labels: size/xs

#53 SDSS-211 - teasers and lists for news, events, basic pages
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/components/basic-page/_basic_page.scss
  themes/sdss_subtheme/src/scss/components/basic-page/index.scss
  themes/sdss_subtheme/src/scss/components/events/_events-list.scss
  themes/sdss_subtheme/src/scss/components/events/_events.scss
  themes/sdss_subtheme/src/scss/components/index.scss
  themes/sdss_subtheme/src/scss/components/news/_news-list.scss
  themes/sdss_subtheme/src/scss/components/news/_news.scss
Labels: size/xs

#56 SDSS-000: Menu depth updates
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/components/main-navigation/_main-navigation.scss
  themes/sdss_subtheme/templates/menus/macros/nav-menu.twig
Labels: size/xs
