Repository SU-SWS/sdss_profile, pull requests merged in 2022-07, with the labels that each got.

#21 20220714 Stanford Profile updates
  composer.json
  config/sync/core.entity_view_display.media.embeddable.default.yml
  config/sync/field.field.media.embeddable.field_media_embeddable_code.yml
  config/sync/filter.format.stanford_html.yml
  config/sync/media.type.embeddable.yml
  config/sync/views.view.search.yml
  modules/stanford_events/modules/stanford_events_importer/src/Plugin/Field/FieldWidget/StanfordEventsImporterAPIURLFieldWidget.php
  modules/stanford_events/pdb_components/mini-calendar/build/static/css/main.css
  modules/stanford_events/pdb_components/mini-calendar/src/styles.scss
  modules/stanford_intranet/src/Config/ConfigOverrider.php
  modules/stanford_profile_styles/dist/css/base/admin/ckeditor.css
  modules/stanford_profile_styles/dist/css/base/admin/field_widgets.css
  modules/stanford_profile_styles/dist/css/base/admin/node_forms.css
  modules/stanford_profile_styles/dist/css/base/stanford_profile_styles.css
  modules/stanford_profile_styles/dist/css/base/views/search.css
  modules/stanford_profile_styles/dist/css/component/blocks/config_pages.super-footer.css
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.layout.full-width.css
  modules/stanford_profile_styles/dist/css/component/paragraph/gallery.css
  modules/stanford_profile_styles/dist/css/component/paragraph/react_paragraphs.css
  modules/stanford_profile_styles/dist/css/component/paragraph/spacer.css
  modules/stanford_profile_styles/dist/css/component/paragraph/wysiwyg.css
  modules/stanford_profile_styles/dist/css/layout/layout.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
  tests/codeception/acceptance/Content/EventsCest.php
  tests/codeception/acceptance/Content/NewsCest.php
  tests/codeception/acceptance/LocalFooter/LocalFooterCest.php
  tests/codeception/acceptance/Media/MediaCest.php
  tests/codeception/acceptance/SystemSiteConfigCest.php
  tests/codeception/functional/Content/BasicPageParagraphsCest.php
  tests/codeception/functional/Content/StanfordNewsCest.php
Labels: size/xl

#23 Added basic public protection.
  themes/sdss_subtheme/sdss_subtheme.theme
  themes/sdss_subtheme/templates/html.html.twig
Labels: size/xs

#22 fixup to have the image appear and comments
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/components/news/_news-list.scss
Labels: size/xs

#25 Stanford profile updates 20220728
  composer.json
  config/sync/block.block.config_pages.yml
  config/sync/block.block.minimally_branded_subtheme_config_pages.yml
  config/sync/block.block.minimally_branded_subtheme_config_pages_stanford_global_msg.yml
  config/sync/block.block.minimally_branded_subtheme_config_pages_stanford_super_footer.yml
  config/sync/block.block.stanford_basic_config_pages_stanford_global_msg.yml
  config/sync/block.block.stanford_basic_config_pages_stanford_super_footer.yml
  config/sync/core.entity_form_display.media.google_form.default.yml
  config/sync/core.entity_form_display.media.google_form.media_library.yml
  config/sync/core.entity_form_display.media.image.media_library.yml
  config/sync/core.entity_form_display.media.stanford_gallery_images.media_library.yml
  config/sync/core.entity_form_display.media.video.default.yml
  config/sync/core.entity_form_display.node.stanford_course.default.yml
  config/sync/core.entity_form_display.node.stanford_page.default.yml
  config/sync/core.entity_view_display.node.stanford_course.default.yml
  config/sync/core.entity_view_display.node.stanford_course.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_course.teaser.yml
  config/sync/core.entity_view_display.node.stanford_event.default.yml
  config/sync/core.entity_view_display.node.stanford_event_series.default.yml
  config/sync/core.entity_view_display.node.stanford_news.default.yml
  config/sync/core.entity_view_display.node.stanford_page.default.yml
  config/sync/core.entity_view_display.node.stanford_person.default.yml
  config/sync/core.entity_view_display.node.stanford_publication.default.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_event_types.default.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_news_topics.default.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_person_types.default.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_publication_topics.default.yml
  config/sync/core.entity_view_display.taxonomy_term.su_course_quarters.default.yml
  config/sync/core.entity_view_display.taxonomy_term.su_course_subjects.default.yml
  config/sync/field.storage.config_pages.su_person_cap_password.yml
  config/sync/field.storage.config_pages.su_person_cap_username.yml
  config/sync/field_encrypt.settings.yml
  config/sync/rabbit_hole.behavior_settings.node_type_stanford_course.yml
  config/sync/rabbit_hole.behavior_settings.node_type_stanford_event.yml
  config/sync/rabbit_hole.behavior_settings.node_type_stanford_news.yml
  config/sync/rabbit_hole.behavior_settings.node_type_stanford_person.yml
  config/sync/search_api.index.full_site_content.yml
  config/sync/ultimate_cron.job.field_encrypt_cron.yml
  config/sync/views.view.search.yml
  config/sync/views.view.stanford_courses.yml
  config/sync/xmlsitemap_engines.settings.yml
  modules/stanford_courses/stanford_courses.module
  modules/stanford_events/stanford_events.module
  modules/stanford_intranet/tests/src/Kernel/IntranetKernelTestBase.php
  modules/stanford_news/stanford_news.module
  modules/stanford_profile_helper/src/EventSubscriber/EntityEventSubscriber.php
  modules/stanford_profile_helper/stanford_profile_helper.info.yml
  modules/stanford_profile_helper/stanford_profile_helper.module
  modules/stanford_profile_helper/stanford_profile_helper.services.yml
  modules/stanford_profile_helper/templates/rabbit-hole-message.html.twig
  modules/stanford_profile_helper/tests/src/Kernel/EventSubscriber/EntityEventSubscriberTest.php
  modules/stanford_profile_helper/tests/src/Kernel/EventSubscriber/test.html
  modules/stanford_profile_helper/tests/src/Kernel/MenuActiveTrailsCacheContextOverrideTest.php
  modules/stanford_profile_helper/tests/src/Kernel/MenuLinkTreeOverrideTest.php
  modules/stanford_profile_helper/tests/src/Kernel/Plugin/Field/FieldWidget/SamlRoleMappingWidgetTest.php
  modules/stanford_text_editor/config/install/editor.editor.stanford_minimal_html.yml
  modules/stanford_text_editor/tests/src/Kernel/StanfordTextEditorTest.php
  tests/codeception/acceptance/Content/CoursesCest.php
  themes/stanford_basic/templates/node.html.twig
  themes/stanford_basic/templates/rabbit-hole-message.html.twig
Labels: size/m

#26 SDSS-34: changes to secondary navigation
  themes/sdss_subtheme/dist/assets/svg/caret-down-green.svg
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/sdss_subtheme.react_behaviors.yml
  themes/sdss_subtheme/src/assets/svg/caret-down-green.svg
  themes/sdss_subtheme/src/scss/components/row-backgrounds/_row-background-colors.scss
  themes/sdss_subtheme/src/scss/components/secondary-navigation/_secondary-navigation.scss
  themes/sdss_subtheme/src/scss/theme/_headings.scss
  themes/sdss_subtheme/src/scss/theme/_link.scss
  themes/sdss_subtheme/src/scss/utilities/variables/_colors.scss
  themes/sdss_subtheme/templates/components/local-footer/pattern-localfooter.html.twig
  themes/sdss_subtheme/templates/components/menus/menu--secondary-nav.html.twig
Labels: size/s

#27 fix the font size and headings
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/theme/_headings.scss
  themes/sdss_subtheme/src/scss/theme/_wysiwyg.scss
Labels: size/xs
