Repository SU-SWS/sdss_profile, pull requests merged in 2022-09, with the labels that each got.

#60 2022-09-06: stanford_profile updates
  composer.json
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/src/Plugin/Field/FieldWidget/ExploreCoursesUrlWidget.php
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_courses/tests/src/Kernel/Plugin/Field/FieldWidget/ExploreCoursesUrlWidgetTest.php
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/modules/stanford_image_styles_preview/stanford_image_styles_preview.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_helper/stanford_profile_helper.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  themes/minimally_branded_subtheme/minimally_branded_subtheme.info.yml
  themes/stanford_basic/stanford_basic.info.yml
Labels: size/xs

#59 SDSS-247: Added class for animated gif workaround.
  config/sync/config_split.config_split.acsf.yml
  config/sync/config_split.config_split.dev.yml
  config/sync/config_split.config_split.local.yml
  config/sync/config_split.config_split.prod.yml
  config/sync/config_split.config_split.stage.yml
  config/sync/field.field.paragraph.stanford_banner.su_banner_button.yml
  config/sync/field.field.paragraph.stanford_card.su_card_link.yml
  config/sync/field.field.paragraph.stanford_entity.su_entity_button.yml
  config/sync/field.field.paragraph.stanford_lists.su_list_button.yml
  config/sync/field.field.paragraph.stanford_media_caption.su_media_caption_link.yml
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/components/all/_vertical-spacing.scss
Labels: size/xs

#61 Release 1.0.1
  CHANGELOG.md
  composer.json
  config/sync/config_split.config_split.acsf.yml
  config/sync/config_split.config_split.dev.yml
  config/sync/config_split.config_split.local.yml
  config/sync/config_split.config_split.prod.yml
  config/sync/config_split.config_split.stage.yml
  config/sync/field.field.paragraph.stanford_banner.su_banner_button.yml
  config/sync/field.field.paragraph.stanford_card.su_card_link.yml
  config/sync/field.field.paragraph.stanford_entity.su_entity_button.yml
  config/sync/field.field.paragraph.stanford_lists.su_list_button.yml
  config/sync/field.field.paragraph.stanford_media_caption.su_media_caption_link.yml
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/src/Plugin/Field/FieldWidget/ExploreCoursesUrlWidget.php
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_courses/tests/src/Kernel/Plugin/Field/FieldWidget/ExploreCoursesUrlWidgetTest.php
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/modules/stanford_image_styles_preview/stanford_image_styles_preview.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_helper/stanford_profile_helper.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  sdss_profile.info.yml
  themes/minimally_branded_subtheme/minimally_branded_subtheme.info.yml
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/sdss_subtheme.info.yml
  themes/sdss_subtheme/src/scss/components/all/_vertical-spacing.scss
  themes/stanford_basic/stanford_basic.info.yml
Labels: size/s

#63 SDSS-257: hover and focus on events
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/theme/_wysiwyg.scss
Labels: size/xs

#64 SDSS-270: Add news RSS
  composer.json
  config/sync/core.extension.yml
  config/sync/migrate_plus.migration.stanford_events_importer.yml
  config/sync/views.view.rss_feeds.yml
Labels: size/m

#65 Release 1.0.2
  CHANGELOG.md
  composer.json
  config/sync/core.extension.yml
  config/sync/migrate_plus.migration.stanford_events_importer.yml
  config/sync/views.view.rss_feeds.yml
  sdss_profile.info.yml
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/sdss_subtheme.info.yml
  themes/sdss_subtheme/src/scss/theme/_wysiwyg.scss
Labels: size/m
