Repository SU-SWS/sdss_profile, pull requests merged in 2022-12, with the labels that each got.

#92 Added jsonapi_hypermedia module
  composer.json
Labels: size/xs

#91 SDSS-398: Updated stanford_circle mask image path.
  config/sync/image.style.stanford_circle.yml
Labels: size/xs

#84 SDSS-363: Replaced dek with dek long in news list view pattern.
  config/sync/core.entity_view_display.node.stanford_news.stanford_card.yml
  config/sync/views.view.stanford_news.yml
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/src/scss/components/news/_news-list.scss
  themes/sdss_subtheme/src/scss/components/news/_news.scss
  themes/sdss_subtheme/templates/components/news-list/news-item-list.html.twig
  themes/sdss_subtheme/templates/components/news-list/news-list.ui_patterns.yml
  themes/sdss_subtheme/templates/components/news-vertical-teaser/pattern-news-vertical-teaser.html.twig
  themes/sdss_subtheme/templates/components/news-vertical-teaser/pattern-news-vertical-teaser.ui_patterns.yml
Labels: size/l

#90 SDSS-386: changes to the main school masthead.
  themes/sdss_subtheme/dist/assets/png/sdss-lock-up-color-small_0.png
  themes/sdss_subtheme/dist/assets/svg/magnifying-glass-24px-white.svg
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/dist/js/scripts.js
  themes/sdss_subtheme/dist/js/scripts.js.map
  themes/sdss_subtheme/src/assets/png/sdss-lock-up-color-small_0.png
  themes/sdss_subtheme/src/assets/svg/magnifying-glass-24px-white.svg
  themes/sdss_subtheme/src/js/sdss_subtheme.behaviors.js
  themes/sdss_subtheme/src/scss/components/header/_header.scss
  themes/sdss_subtheme/src/scss/components/header/index.scss
  themes/sdss_subtheme/src/scss/components/index.scss
  themes/sdss_subtheme/src/scss/components/lockup/_lockup.scss
  themes/sdss_subtheme/src/scss/components/main-navigation/_main-navigation.scss
  themes/sdss_subtheme/src/scss/components/main-navigation/_wrapper.scss
  themes/sdss_subtheme/src/scss/components/search/_search.scss
  themes/sdss_subtheme/templates/components/search/block--stanford-basic-search.html.twig
  themes/sdss_subtheme/templates/menus/menu--main.html.twig
  themes/sdss_subtheme/templates/page.html.twig
Labels: size/s

#94 Release 1.1.2
  CHANGELOG.md
  composer.json
  config/sync/core.entity_view_display.node.stanford_news.stanford_card.yml
  config/sync/field.field.node.stanford_news.su_sdss_news_news_source.yml
  config/sync/image.style.stanford_circle.yml
  config/sync/views.view.stanford_news.yml
  sdss_profile.info.yml
  themes/sdss_subtheme/dist/assets/png/sdss-lock-up-color-small_0.png
  themes/sdss_subtheme/dist/assets/svg/magnifying-glass-24px-white.svg
  themes/sdss_subtheme/dist/css/sdss_subtheme.css
  themes/sdss_subtheme/dist/js/scripts.js
  themes/sdss_subtheme/dist/js/scripts.js.map
  themes/sdss_subtheme/sdss_subtheme.info.yml
  themes/sdss_subtheme/src/assets/png/sdss-lock-up-color-small_0.png
  themes/sdss_subtheme/src/assets/svg/magnifying-glass-24px-white.svg
  themes/sdss_subtheme/src/js/sdss_subtheme.behaviors.js
  themes/sdss_subtheme/src/scss/components/header/_header.scss
  themes/sdss_subtheme/src/scss/components/header/index.scss
  themes/sdss_subtheme/src/scss/components/index.scss
  themes/sdss_subtheme/src/scss/components/lockup/_lockup.scss
  themes/sdss_subtheme/src/scss/components/main-navigation/_main-navigation.scss
  themes/sdss_subtheme/src/scss/components/main-navigation/_wrapper.scss
  themes/sdss_subtheme/src/scss/components/news/_news-list.scss
  themes/sdss_subtheme/src/scss/components/news/_news.scss
  themes/sdss_subtheme/src/scss/components/search/_search.scss
  themes/sdss_subtheme/templates/components/news-list/news-item-list.html.twig
  themes/sdss_subtheme/templates/components/news-list/news-list.ui_patterns.yml
  themes/sdss_subtheme/templates/components/news-vertical-teaser/pattern-news-vertical-teaser.html.twig
  themes/sdss_subtheme/templates/components/news-vertical-teaser/pattern-news-vertical-teaser.ui_patterns.yml
  themes/sdss_subtheme/templates/components/search/block--stanford-basic-search.html.twig
  themes/sdss_subtheme/templates/menus/menu--main.html.twig
  themes/sdss_subtheme/templates/page.html.twig
  themes/stanford_basic/theme-settings.php
Labels: size/l

#102 SDSS-247: Removed trim from external url field on news card display.
  config/sync/core.entity_view_display.node.stanford_news.stanford_card.yml
Labels: size/xs

#103 SDSS-435: Configured fast_404 and page_cache_query_ignore
  composer.json
  config/sync/core.extension.yml
  config/sync/editoria11y.configuration.yml
  config/sync/page_cache_query_ignore.settings.yml
Labels: size/xs

#104 Release 1.1.4
  CHANGELOG.md
  composer.json
  config/sync/core.entity_view_display.node.stanford_news.stanford_card.yml
  config/sync/core.extension.yml
  config/sync/editoria11y.configuration.yml
  config/sync/page_cache_query_ignore.settings.yml
  sdss_profile.info.yml
  themes/sdss_subtheme/sdss_subtheme.info.yml
Labels: size/xs

#105 Backtodev 1.1.5
  CHANGELOG.md
  sdss_profile.info.yml
  themes/sdss_subtheme/sdss_subtheme.info.yml
Labels: size/xs
